fixed reporting

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -20,18 +20,19 @@ jobs:
 
       - name: Run Docker Compose with Tests
         run: |
-            cd gideon
-            docker-compose up
-            exit_code=$?
-            if [ $exit_code -ne 0 ]; then
-            echo "::error::Docker Compose command failed with exit code $exit_code"
-            exit $exit_code
-            fi
+          cd gideon
+          docker-compose up
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+          echo "::error::Docker Compose command failed with exit code $exit_code"
+          exit $exit_code
+          fi
 
-      - name: Report Success
-        if: success()
-        run: echo "Tests passed successfully!"
-
-      - name: Report Failure
-        if: failure()
-        run: echo "Tests failed!"
+      - name: Report Results
+        run: |
+          if [ ${{ job.status }} == 'success' ]; then
+            echo "Tests passed successfully!"
+          else
+            echo "Tests failed!"
+            exit 1
+          fi
